name: .NET Build, Test, and Publish Nuget Package

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types:
      - "published"
env:
  VERSION: 1.0.0

defaults:
  run:
    working-directory: src
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Version
      if: github.ref_type == 'tag'
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=$TAG" >> $GITHUB_ENV 
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -p:Version=$VERSION 
    - name: pack nuget packages
      if: github.ref_type == 'tag'
      run: dotnet pack --output nupkgs --no-restore --no-build -p:PackageVersion=$VERSION
    - name: upload nuget package
      if: github.ref_type == 'tag'
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

